AllCops:
  Exclude:
    - 'config/*'
    - 'bin/*'
    - 'vendor/**/*'

Style/Documentation:
  Enabled: false

Lint/MissingSuper:
  Exclude:
    - 'app/components/**/*'

Metrics/MethodLength:
  Enabled: true
  Max: 15
